version: "3.9"

services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: "kafka:9092"
    depends_on:
      - kafka

  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      ALLOW_PLAINTEXT_LISTENER: "yes"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f -X GET 'http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 12

  kibana:
    container_name: kib
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

  extractor:
    build:
      context: .
      dockerfile: extractor/Dockerfile
    container_name: extractor
    environment:
      KAFKA_BROKER_URL: kafka:9092
      DIRECTORY_PATH: /app/podcasts
      ES_HOST: http://elasticsearch:9200
    ports:
      - "8001:8001"
    volumes:
      - "C:/Users/eliwa/podcasts_project/podcasts:/app/podcasts"
    depends_on:
      elasticsearch:
        condition: service_healthy

  persister:
    build:
      context: .
      dockerfile: persister/Dockerfile
    container_name: persister
    environment:
      KAFKA_BROKER_URL: kafka:9092
      DIRECTORY_PATH: /app/podcasts
      MDB_HOST: mongodb:27017
      DB_NAME: podcasts_data
      ES_HOST: http://elasticsearch:9200
    ports:
      - "8002:8002"
    volumes:
      - "C:/Users/eliwa/podcasts_project/podcasts:/app/podcasts"
    depends_on:
      elasticsearch:
        condition: service_healthy

  stt_service:
    build:
      context: .
      dockerfile: stt_service/Dockerfile
    container_name: stt_service
    environment:
      KAFKA_BROKER_URL: kafka:9092
#      DIRECTORY_PATH: /app/podcasts
      MDB_HOST: mongodb:27017
      DB_NAME: podcasts_data
      ES_HOST: http://elasticsearch:9200
    ports:
      - "8003:8003"
    depends_on:
      elasticsearch:
        condition: service_healthy


volumes:
  mongo_data:


